// TEC Connection (C-107) — the PUBLIC shareable profile.
//
// This page is the app's cheapest acquisition surface: a Pi user pastes
// connection.tecosystem.app/u/<handle> into a group chat and everyone who taps it
// lands here with no session. So it has to stand on its own — say who this is,
// why the badge means something, and give one obvious way in.
//
// Verification is PRESENTED from Zone / KYC and never minted here; Featured is a
// Connection Pro placement worth reach only. 404 when the handle is unknown or
// unpublished — a preview must never imply a profile exists.
import Link from 'next/link';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { resolvePublicProfile } from '@/lib/connection/discovery';
import { Avatar } from '@/components/public/Avatar';

export const dynamic = 'force-dynamic';

// A shared profile link was previously blind: pasted into WhatsApp, Telegram or X
// it previewed as the generic app title with no name, no headline and no image.
// For the app that is meant to be the ecosystem's front door, the shared link IS
// the acquisition surface — so it carries the person's own identity. The matching
// card image is generated by ./opengraph-image.tsx.
export async function generateMetadata(
  { params }: { params: Promise<{ username: string }> },
): Promise<Metadata> {
  const { username } = await params;
  const p = await resolvePublicProfile(username);
  if (!p) return { title: 'Profile not found · TEC Connection' };

  const title       = `@${p.username} · TEC Connection`;
  const description = p.headline
    ? p.headline
    : `@${p.username} — ${p.category} in the Pi economy. ${p.followers} follower${p.followers === 1 ? '' : 's'}.`;

  return {
    title,
    description,
    openGraph: { title, description, type: 'profile' },
    twitter:   { card: 'summary_large_image', title, description },
  };
}

const fmtSince = (iso?: string): string | null => {
  if (!iso) return null;
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? null : d.toLocaleDateString('en', { month: 'long', year: 'numeric' });
};

export default async function PublicProfilePage({ params }: { params: Promise<{ username: string }> }) {
  const { username } = await params;
  const p = await resolvePublicProfile(username);
  if (!p) notFound();

  const since = fmtSince(p.since);

  return (
    <main className="pub-glow" style={{
      minHeight: '100vh', color: '#fff',
      fontFamily: 'var(--font-sans, system-ui, -apple-system, sans-serif)', overflowX: 'hidden',
    }}>
      <div style={{
        maxWidth: 480, margin: '0 auto',
        padding: 'calc(34px + env(safe-area-inset-top)) 22px calc(56px + env(safe-area-inset-bottom))',
      }}>

        <Link href="/discover" className="pub-eyebrow" style={{ textDecoration: 'none', display: 'inline-block' }}>
          ← Discover
        </Link>

        <section className="pub-panel pub-in" style={{ marginTop: 18, padding: '34px 26px', textAlign: 'center' }}>
          <div style={{ display: 'flex', justifyContent: 'center' }}>
            <Avatar username={p.username} size={84} />
          </div>

          <h1 style={{
            fontSize: 'clamp(24px, 7vw, 30px)', fontWeight: 900, letterSpacing: '-0.02em',
            color: '#fff', margin: '18px 0 0',
          }}>@{p.username}</h1>

          <div style={{ display: 'flex', gap: 7, justifyContent: 'center', flexWrap: 'wrap', marginTop: 10 }}>
            {p.verified && (
              <span className="pub-badge-verified" title="Verified — presented from Zone / KYC, never minted by Connection">
                ✓ Verified
              </span>
            )}
            {p.featured && (
              <span className="pub-badge-featured" title="Featured — a Connection Pro placement. Reach only; not verification.">
                Featured
              </span>
            )}
            <span className="pub-badge-featured" style={{ textTransform: 'capitalize' }}>{p.category}</span>
          </div>

          {p.headline && (
            <p style={{
              fontSize: 15, lineHeight: 1.6, color: 'rgba(255,255,255,0.68)',
              margin: '18px auto 0', maxWidth: 340,
            }}>{p.headline}</p>
          )}

          {/* Followers is the only number this page can state, and it comes from a
              real count of real edges — so it is stated, and nothing else is. */}
          <div style={{
            display: 'inline-flex', alignItems: 'baseline', gap: 8,
            margin: '24px 0 0', padding: '12px 22px', borderRadius: 14,
            background: 'rgba(255,255,255,0.04)', border: '1px solid var(--tec-border)',
          }}>
            <span style={{ fontSize: 24, fontWeight: 900, color: 'var(--tec-gold)' }}>{p.followers}</span>
            <span style={{ fontSize: 12.5, fontWeight: 650, color: 'rgba(255,255,255,0.5)' }}>
              follower{p.followers === 1 ? '' : 's'}
            </span>
          </div>

          {since && (
            <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.34)', marginTop: 12 }}>
              On TEC since {since}
            </div>
          )}

          <div style={{ marginTop: 26 }}>
            <Link href="/app" className="pub-cta" style={{ textDecoration: 'none' }}>
              Follow @{p.username}
            </Link>
          </div>
          <Link href="/discover" className="pub-secondary">
            Browse more people →
          </Link>
        </section>

        <p style={{
          fontSize: 11.5, color: 'rgba(255,255,255,0.34)', marginTop: 20,
          textAlign: 'center', lineHeight: 1.65,
        }}>
          Verification is presented from Zone / KYC — never minted by Connection.
          Featured is a Connection Pro placement: reach only, never trust.
          Trust is earned, never bought.
        </p>
      </div>
    </main>
  );
}
